// Build step — transform + minify the JSX sources into a single classic-script
// bundle.js that the static site loads directly. This replaces the old setup
// that shipped @babel/standalone and transpiled the JSX in the browser on every
// page load (multi-second main-thread freeze on phones).
//
// React / ReactDOM are loaded separately as production UMD globals from the CDN
// in index.html, so they're treated as ambient here (not bundled).
//
// Run `npm run build` after editing gauges.jsx or app.jsx. The committed
// bundle.js is the artifact the page actually uses.
import { transform } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';

// Load order matters: gauges.jsx defines window.PW* before app.jsx consumes them.
const inputs = ['gauges.jsx', 'app.jsx'];
const sources = await Promise.all(
  inputs.map((f) => readFile(new URL(f, import.meta.url), 'utf8'))
);
const combined = sources.join('\n;\n');

const { code, warnings } = await transform(combined, {
  loader: 'jsx',
  jsx: 'transform',                 // classic runtime — emits React.createElement
  jsxFactory: 'React.createElement', // resolved against the global `React`
  jsxFragment: 'React.Fragment',
  minify: true,
  target: ['es2019'],
  legalComments: 'none',
});
for (const w of warnings) console.warn('esbuild:', w.text);

const banner = '/* AUTO-GENERATED by `npm run build` from gauges.jsx + app.jsx — do not edit. */\n';
await writeFile(new URL('bundle.js', import.meta.url), banner + code);
console.log(`bundle.js written (${((banner.length + code.length) / 1024).toFixed(1)} KB)`);
